version: "3"
services:
  voltronic-mqtt:
    container_name: "voltronic-mqtt"
    image: "voltronic-mqtt"
    environment:
      - VERBOSE=2
      - DEVICE_PATH=/dev/ttyUSB0
      - POLLING_INTERVAL=60
      - MQTT_HOST=127.0.0.1:1883
      - MQTT_PASS=user:pass
      - MQTT_CLIENT_ID=voltronic-mqtt
      - MQTT_TOPIC=iot/voltronic
      - MQTT_TOPIC_SUB=send_cmd
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped
    network_mode: host
    privileged: true
