sensor:
  - unique_id: "voltronic_grid_voltage"
    name: "Grid Voltage"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.grid_voltage }}"
    unit_of_measurement: "V"
    icon: "mdi:transmission-tower"
    device_class: voltage
    state_class: measurement
    device:
      # Declare the device here - it can be referenced later by just its identifier :)
      name: "Voltronic"
      identifiers: "voltronic"
  - unique_id: "voltronic_grid_frequency"
    name: "Grid Frequency"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.grid_frequency | float }}"
    unit_of_measurement: "Hz"
    icon: "mdi:transmission-tower"
    device_class: frequency
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_ac_output_voltage"
    name: "AC Output Voltage"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.ac_output_voltage }}"
    unit_of_measurement: "V"
    icon: "mdi:lightning-bolt"
    device_class: voltage
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_ac_output_frequency"
    name: "AC Output Frequency"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.ac_output_frequency }}"
    unit_of_measurement: "Hz"
    icon: "mdi:current-ac"
    device_class: frequency
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_ac_output_apparent_power"
    name: "AC Output Apparent Power"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.ac_output_apparent_power }}"
    unit_of_measurement: "VA"
    icon: "mdi:home-lightning-bolt"
    device_class: apparent_power
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_ac_output_active_power"
    name: "AC Output Active Power"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.ac_output_active_power }}"
    unit_of_measurement: "W"
    icon: "mdi:home-lightning-bolt"
    device_class: power
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_output_load_percent"
    name: "Output Load Percent"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.output_load_percent }}"
    unit_of_measurement: "%"
    icon: "mdi:brightness-percent"
    device_class: power_factor
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_battery_voltage"
    name: "Battery Voltage"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.battery_voltage }}"
    unit_of_measurement: "V"
    icon: "mdi:lightning-bolt"
    device_class: voltage
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_battery_charging_current"
    name: "Battery Charging Current"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.battery_charging_current }}"
    unit_of_measurement: "A"
    icon: "mdi:current-dc"
    device_class: current
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_battery_capacity"
    name: "Battery Capacity"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.battery_capacity }}"
    unit_of_measurement: "%"
    icon: "mdi:battery-outline"
    device_class: battery
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_pv_input_current"
    name: "PV Input Current"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.pv_input_current }}"
    unit_of_measurement: "A"
    icon: "mdi:current-dc"
    device_class: current
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_pv_input_voltage"
    name: "PV Input Voltage"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.pv_input_voltage }}"
    unit_of_measurement: "V"
    icon: "mdi:solar-power"
    device_class: voltage
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_battery_discharge_current"
    name: "Battery Discharge Current"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.battery_discharge_current }}"
    unit_of_measurement: "A"
    icon: "mdi:current-dc"
    device_class: current
    state_class: measurement
    device:
      identifiers: "voltronic"
  - unique_id: "voltronic_pv_charging_power"
    name: "PV Charging Power"
    state_topic: "iot/voltronic/qpigs"
    value_template: "{{ value_json.pv_charging_power }}"
    unit_of_measurement: "W"
    icon: "mdi:solar-power-variant"
    device_class: power
    state_class: measurement
    device:
      identifiers: "voltronic"

select:
  - unique_id: "voltronic_output_source_priority"
    name: "Output Source Priority"
    state_topic: "iot/voltronic/qpiri"
    optimistic: false
    value_template: >-
      {% set options = ["Utility First", "Solar First", "SBU"] %}
      0{{ value_json.output_source_priority }} ({{ options[value_json.output_source_priority] }})
    command_topic: "iot/voltronic/send_cmd"
    command_template: POP{{ value[:2] }}
    options:
      - "00 (Utility First)"
      - "01 (Solar First)"
      - "02 (SBU)"
    device:
      identifiers: "voltronic"

